GLOBAL.setfenv(1, GLOBAL)

STRINGS.UI.RARITY.Glassic = "Glassic"

STRINGS.NAMES.MOONGLASSPICKAXE = "Moon Glass Pickaxe"
STRINGS.RECIPE_DESC.MOONGLASSPICKAXE = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSPICKAXE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.NAMES.MOONGLASSHAMMER = "Moon Glass Hammer"
STRINGS.RECIPE_DESC.MOONGLASSHAMMER = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSHAMMER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.SKIN_NAMES.goldenaxe_victorian = "Ornate Fanciful Axe"
STRINGS.SKIN_NAMES.moonglassaxe_northern = "Moon Nordic Axe"
STRINGS.SKIN_NAMES.moonglassaxe_victorian = "Moon Fanciful Axe"
STRINGS.SKIN_NAMES.moonglasshammer_forge = "Moon Forging Hammer"
STRINGS.SKIN_NAMES.moonglasspickaxe_northern = "Moon Nordic Pickaxe"

STRINGS.SKIN_NAMES.glassiccutter_dream = "Musou Isshin"

STRINGS.NAMES.GLASSICCUTTER = "Glassic Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONGLASS = "Gestalt Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONROCK = "Frost Cutter"
STRINGS.NAMES.GLASSICCUTTER_DREAM = "Musou Isshin"
STRINGS.NAMES.GLASSICCUTTER_FROST = "Frost Mourning"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSICCUTTER = {
    GENERIC = "Sharp but probably get broken.",
    MOONGLASS = "Sword with gestalt flash.",
    MOONROCK = "Sword with frost energy.",
    DREAM = "Inazuma shines eternal!",
    FROST = "ao?",
}

STRINGS.ANNOUNCE_GLASSICCUTTER_BROKE = "WEAPON BREAK!"
STRINGS.ACTIONS.CHANGE_TACKLE.FRAG = "Set Fragment"
