local STRINGS = GLOBAL.STRINGS

STRINGS.UI.RARITY.Glassic = "Glassic"

STRINGS.NAMES.MOONGLASSPICKAXE = "Moon Glass Pickaxe"
STRINGS.RECIPE_DESC.MOONGLASSPICKAXE = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSPICKAXE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.NAMES.MOONGLASSHAMMER = "Moon Glass Hammer"
STRINGS.RECIPE_DESC.MOONGLASSHAMMER = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSHAMMER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.SKIN_NAMES.goldenaxe_victorian = "Ornate Fanciful Axe"
STRINGS.SKIN_NAMES.moonglassaxe_northern = "Moon Nordic Axe"
STRINGS.SKIN_NAMES.moonglassaxe_victorian = "Moon Fanciful Axe"
STRINGS.SKIN_NAMES.moonglasshammer_forge = "Moon Forging Hammer"
STRINGS.SKIN_NAMES.moonglasspickaxe_northern = "Moon Nordic Pickaxe"

STRINGS.NAMES.GLASSICCUTTER = "Glassic Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONGLASS = "Gestalt Cutter"
STRINGS.NAMES.GLASSICCUTTER_THULECITE = "Thulecite Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONROCK = "Frost Cutter"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSICCUTTER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSCUTTER