GLOBAL.setfenv(1, GLOBAL)

STRINGS.UI.RARITY.Glassic = "Glassic"

STRINGS.NAMES.MOONGLASSPICKAXE = "Moon Glass Pickaxe"
STRINGS.RECIPE_DESC.MOONGLASSPICKAXE = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSPICKAXE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.NAMES.MOONGLASSHAMMER = "Moon Glass Hammer"
STRINGS.RECIPE_DESC.MOONGLASSHAMMER = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSHAMMER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.SKIN_NAMES.goldenaxe_victorian = "Ornate Fanciful Axe"
STRINGS.SKIN_NAMES.moonglassaxe_northern = "Moon Nordic Axe"
STRINGS.SKIN_NAMES.moonglassaxe_victorian = "Moon Fanciful Axe"
STRINGS.SKIN_NAMES.moonglasshammer_forge = "Moon Forging Hammer"
STRINGS.SKIN_NAMES.moonglasspickaxe_northern = "Moon Nordic Pickaxe"

STRINGS.SKIN_NAMES.glassiccutter_dream = "Musou Isshin"

STRINGS.NAMES.GLASSICCUTTER = "Glassic Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONGLASS = "Gestalt Cutter"
STRINGS.NAMES.GLASSICCUTTER_THULECITE = "Thulecite Cutter"
STRINGS.NAMES.GLASSICCUTTER_MOONROCK = "Frost Cutter"
STRINGS.NAMES.GLASSICCUTTER_DREAM = "Musou Isshin"
STRINGS.NAMES.GLASSICCUTTER_EXCALIBUR = "Excalibur"
STRINGS.NAMES.GLASSICCUTTER_FROSTMOURNING = "Frost Mourning"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSICCUTTER = {
    -- GENERIC = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSCUTTER,
    NONE = "Sharp but probably get broken.",
    MOONGLASS = "Sword with gestalt flash.",
    THULECITE = "Sword with ancient power.",
    MOONROCK = "Sword with frost energy.",
    DREAM = "Inazuma shines eternal!",
    EXCALIBUR = "Sheathed in the breath of the planet, a torrent of shining life. Feel its wrath.",
    FROSTMOURNING = "ao?",
}

STRINGS.ANNOUNCE_GLASSICCUTTER_BROKE = "WEAPON BREAK!"
