local STRINGS = GLOBAL.STRINGS

STRINGS.UI.RARITY.Glassic = "玻璃制品"

STRINGS.NAMES.MOONGLASSPICKAXE = "月镜片镐"
STRINGS.RECIPE_DESC.MOONGLASSPICKAXE = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSPICKAXE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.NAMES.MOONGLASSHAMMER = "月镜片锤"
STRINGS.RECIPE_DESC.MOONGLASSHAMMER = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSHAMMER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.SKIN_NAMES.goldenaxe_victorian = "怪诞的金斧子"
STRINGS.SKIN_NAMES.moonglassaxe_northern = "华丽的玻璃斧"
STRINGS.SKIN_NAMES.moonglassaxe_victorian = "怪诞的玻璃斧"
STRINGS.SKIN_NAMES.moonglasspickaxe_northern = "华丽的月光鹤嘴锄"
STRINGS.SKIN_NAMES.moonglasshammer_forge = "月神锤"

STRINGS.SKIN_NAMES.glassiccutter_dream = "梦想一心"

STRINGS.NAMES.GLASSICCUTTER = "玻璃制刀"
STRINGS.NAMES.GLASSICCUTTER_MOONGLASS = "月灵刀"
STRINGS.NAMES.GLASSICCUTTER_THULECITE = "古灵刀"
STRINGS.NAMES.GLASSICCUTTER_MOONROCK = "霜灵刀"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSICCUTTER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSCUTTER