GLOBAL.setfenv(1, GLOBAL)

STRINGS.UI.RARITY.Glassic = "玻璃制品"

STRINGS.NAMES.MOONGLASSPICKAXE = "月光玻璃镐"
STRINGS.RECIPE_DESC.MOONGLASSPICKAXE = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSPICKAXE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.NAMES.MOONGLASSHAMMER = "月光玻璃锤"
STRINGS.RECIPE_DESC.MOONGLASSHAMMER = STRINGS.RECIPE_DESC.MOONGLASSAXE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSHAMMER = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE

STRINGS.SKIN_NAMES.goldenaxe_victorian = "怪诞的金斧子"
STRINGS.SKIN_NAMES.moonglassaxe_northern = "华丽的玻璃斧"
STRINGS.SKIN_NAMES.moonglassaxe_victorian = "怪诞的玻璃斧"
STRINGS.SKIN_NAMES.moonglasspickaxe_northern = "华丽的月光鹤嘴锄"
STRINGS.SKIN_NAMES.moonglasshammer_forge = "月神锤"

STRINGS.SKIN_NAMES.glassiccutter_dream = "梦想一心"

STRINGS.NAMES.GLASSICCUTTER = "玻璃制刀"
STRINGS.NAMES.GLASSICCUTTER_MOONGLASS = "月灵刀"
STRINGS.NAMES.GLASSICCUTTER_THULECITE = "古灵刀"
STRINGS.NAMES.GLASSICCUTTER_MOONROCK = "霜灵刀"
STRINGS.NAMES.GLASSICCUTTER_DREAM = "梦想一心"
STRINGS.NAMES.GLASSICCUTTER_EXCALIBUR = "誓约胜利之剑"
STRINGS.NAMES.GLASSICCUTTER_FROSTMOURNING = "霜之哀嚎"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSICCUTTER = {
    -- GENERIC = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSCUTTER,
    NONE = "很锋利，但很可能很坏掉",
    MOONGLASS = "蕴含了月灵之力的刀刃。",
    THULECITE = "古老的能量使其持久。",
    MOONROCK = "凝结了冰霜之力的刀刃。",
    DREAM = "稻光，亦是永恒！",
    EXCALIBUR = "吾将以骑士荣耀呼唤汝之名。",
    FROSTMOURNING = "嗷？",
}
